/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoId = IDL.Text;
export const EventId = IDL.Text;
export const Photo = IDL.Record({
  'id' : PhotoId,
  'eventId' : EventId,
  'title' : IDL.Text,
  'blobId' : ExternalBlob,
  'uploadedAt' : IDL.Int,
});
export const ServiceHoursId = IDL.Text;
export const VolunteerId = IDL.Text;
export const ServiceHours = IDL.Record({
  'id' : ServiceHoursId,
  'eventId' : EventId,
  'hours' : IDL.Nat,
  'date' : IDL.Int,
  'volunteerId' : VolunteerId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CoordinatorId = IDL.Text;
export const Coordinator = IDL.Record({
  'id' : CoordinatorId,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : EventId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'createdBy' : CoordinatorId,
  'time' : IDL.Int,
  'description' : IDL.Text,
  'requiredHours' : IDL.Nat,
  'location' : IDL.Text,
  'eventType' : IDL.Text,
});
export const NotificationId = IDL.Text;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'targetAll' : IDL.Bool,
  'message' : IDL.Text,
});
export const CertificateId = IDL.Text;
export const Certificate = IDL.Record({
  'id' : CertificateId,
  'hoursCompleted' : IDL.Nat,
  'downloadable' : IDL.Bool,
  'volunteerId' : VolunteerId,
  'issuedAt' : IDL.Int,
});
export const FeedbackId = IDL.Text;
export const Feedback = IDL.Record({
  'id' : FeedbackId,
  'eventId' : IDL.Opt(EventId),
  'submittedAt' : IDL.Int,
  'coordinatorResponse' : IDL.Opt(IDL.Text),
  'volunteerId' : VolunteerId,
  'message' : IDL.Text,
  'respondedAt' : IDL.Opt(IDL.Int),
});
export const Volunteer = IDL.Record({
  'id' : VolunteerId,
  'totalHours' : IDL.Nat,
  'name' : IDL.Text,
  'joinedAt' : IDL.Int,
  'email' : IDL.Text,
  'rollNumber' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const AttendanceId = IDL.Text;
export const Attendance = IDL.Record({
  'id' : AttendanceId,
  'eventId' : EventId,
  'markedBy' : IDL.Text,
  'volunteerId' : VolunteerId,
  'timestamp' : IDL.Int,
});
export const Role = IDL.Variant({
  'coordinator' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'senderRole' : IDL.Text,
  'senderId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [Photo], []),
  'addServiceHours' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
      [ServiceHours],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'checkIfVolunteerAttendedEvent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'createCoordinator' : IDL.Func([IDL.Text, IDL.Text], [Coordinator], []),
  'createCoordinatorAsAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Coordinator],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CoordinatorId,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Text,
      ],
      [Event],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [Notification],
      [],
    ),
  'deleteCoordinator' : IDL.Func([IDL.Text], [], []),
  'deleteCoordinatorAsAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'generateEventAttendanceSummary' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'generateEventAttendanceSummaryAsAdmin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Nat],
      ['query'],
    ),
  'generateVolunteerHoursSummary' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'generateVolunteerHoursSummaryAsAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getAllCoordinators' : IDL.Func([], [IDL.Vec(Coordinator)], ['query']),
  'getAllCoordinatorsAsAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Coordinator)],
      ['query'],
    ),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getAllServiceHoursForEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceHours)],
      ['query'],
    ),
  'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'getAllVolunteersAsAdmin' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Volunteer)],
      ['query'],
    ),
  'getAttendanceForEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Attendance)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertificatesByVolunteer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Certificate)],
      ['query'],
    ),
  'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getCoordinator' : IDL.Func([IDL.Text], [Coordinator], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
  'getMyAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
  'getMyCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
  'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getMyTotalServiceHours' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyVolunteerProfile' : IDL.Func([], [IDL.Opt(Volunteer)], ['query']),
  'getPhotosByEvent' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
  'getServiceHoursByVolunteer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServiceHours)],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVolunteerById' : IDL.Func([IDL.Text], [Volunteer], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'issueCertificate' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Bool],
      [Certificate],
      [],
    ),
  'loginCoordinator' : IDL.Func([IDL.Text], [IDL.Opt(Coordinator)], []),
  'loginVolunteer' : IDL.Func([IDL.Text], [IDL.Opt(Volunteer)], []),
  'manuallyMarkAttendance' : IDL.Func([IDL.Text, IDL.Text], [Attendance], []),
  'markAttendance' : IDL.Func([IDL.Text], [Attendance], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'registerVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Volunteer],
      [],
    ),
  'respondToFeedback' : IDL.Func([IDL.Text, IDL.Text], [Feedback], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
  'submitFeedback' : IDL.Func([IDL.Opt(EventId), IDL.Text], [Feedback], []),
  'updateEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        CoordinatorId,
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Text,
        IDL.Text,
      ],
      [Event],
      [],
    ),
  'updateVolunteerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Volunteer],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoId = IDL.Text;
  const EventId = IDL.Text;
  const Photo = IDL.Record({
    'id' : PhotoId,
    'eventId' : EventId,
    'title' : IDL.Text,
    'blobId' : ExternalBlob,
    'uploadedAt' : IDL.Int,
  });
  const ServiceHoursId = IDL.Text;
  const VolunteerId = IDL.Text;
  const ServiceHours = IDL.Record({
    'id' : ServiceHoursId,
    'eventId' : EventId,
    'hours' : IDL.Nat,
    'date' : IDL.Int,
    'volunteerId' : VolunteerId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CoordinatorId = IDL.Text;
  const Coordinator = IDL.Record({
    'id' : CoordinatorId,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : EventId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'createdBy' : CoordinatorId,
    'time' : IDL.Int,
    'description' : IDL.Text,
    'requiredHours' : IDL.Nat,
    'location' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const NotificationId = IDL.Text;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'targetAll' : IDL.Bool,
    'message' : IDL.Text,
  });
  const CertificateId = IDL.Text;
  const Certificate = IDL.Record({
    'id' : CertificateId,
    'hoursCompleted' : IDL.Nat,
    'downloadable' : IDL.Bool,
    'volunteerId' : VolunteerId,
    'issuedAt' : IDL.Int,
  });
  const FeedbackId = IDL.Text;
  const Feedback = IDL.Record({
    'id' : FeedbackId,
    'eventId' : IDL.Opt(EventId),
    'submittedAt' : IDL.Int,
    'coordinatorResponse' : IDL.Opt(IDL.Text),
    'volunteerId' : VolunteerId,
    'message' : IDL.Text,
    'respondedAt' : IDL.Opt(IDL.Int),
  });
  const Volunteer = IDL.Record({
    'id' : VolunteerId,
    'totalHours' : IDL.Nat,
    'name' : IDL.Text,
    'joinedAt' : IDL.Int,
    'email' : IDL.Text,
    'rollNumber' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const AttendanceId = IDL.Text;
  const Attendance = IDL.Record({
    'id' : AttendanceId,
    'eventId' : EventId,
    'markedBy' : IDL.Text,
    'volunteerId' : VolunteerId,
    'timestamp' : IDL.Int,
  });
  const Role = IDL.Variant({
    'coordinator' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'senderRole' : IDL.Text,
    'senderId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [Photo], []),
    'addServiceHours' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Int],
        [ServiceHours],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'checkIfVolunteerAttendedEvent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'createCoordinator' : IDL.Func([IDL.Text, IDL.Text], [Coordinator], []),
    'createCoordinatorAsAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Coordinator],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CoordinatorId,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Text,
        ],
        [Event],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [Notification],
        [],
      ),
    'deleteCoordinator' : IDL.Func([IDL.Text], [], []),
    'deleteCoordinatorAsAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'generateEventAttendanceSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'generateEventAttendanceSummaryAsAdmin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Nat],
        ['query'],
      ),
    'generateVolunteerHoursSummary' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'generateVolunteerHoursSummaryAsAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getAllCoordinators' : IDL.Func([], [IDL.Vec(Coordinator)], ['query']),
    'getAllCoordinatorsAsAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Coordinator)],
        ['query'],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getAllServiceHoursForEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceHours)],
        ['query'],
      ),
    'getAllVolunteers' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'getAllVolunteersAsAdmin' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Volunteer)],
        ['query'],
      ),
    'getAttendanceForEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Attendance)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertificatesByVolunteer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Certificate)],
        ['query'],
      ),
    'getChatMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getCoordinator' : IDL.Func([IDL.Text], [Coordinator], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Volunteer)], ['query']),
    'getMyAttendance' : IDL.Func([], [IDL.Vec(Attendance)], ['query']),
    'getMyCertificates' : IDL.Func([], [IDL.Vec(Certificate)], ['query']),
    'getMyFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getMyTotalServiceHours' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyVolunteerProfile' : IDL.Func([], [IDL.Opt(Volunteer)], ['query']),
    'getPhotosByEvent' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
    'getServiceHoursByVolunteer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServiceHours)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVolunteerById' : IDL.Func([IDL.Text], [Volunteer], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'issueCertificate' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Bool],
        [Certificate],
        [],
      ),
    'loginCoordinator' : IDL.Func([IDL.Text], [IDL.Opt(Coordinator)], []),
    'loginVolunteer' : IDL.Func([IDL.Text], [IDL.Opt(Volunteer)], []),
    'manuallyMarkAttendance' : IDL.Func([IDL.Text, IDL.Text], [Attendance], []),
    'markAttendance' : IDL.Func([IDL.Text], [Attendance], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'registerVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Volunteer],
        [],
      ),
    'respondToFeedback' : IDL.Func([IDL.Text, IDL.Text], [Feedback], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
    'submitFeedback' : IDL.Func([IDL.Opt(EventId), IDL.Text], [Feedback], []),
    'updateEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          CoordinatorId,
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Text,
          IDL.Text,
        ],
        [Event],
        [],
      ),
    'updateVolunteerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Volunteer],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };