/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'id' : AttendanceId,
  'eventId' : EventId,
  'markedBy' : string,
  'volunteerId' : VolunteerId,
  'timestamp' : bigint,
}
export type AttendanceId = string;
export interface Certificate {
  'id' : CertificateId,
  'hoursCompleted' : bigint,
  'downloadable' : boolean,
  'volunteerId' : VolunteerId,
  'issuedAt' : bigint,
}
export type CertificateId = string;
export interface ChatMessage {
  'id' : string,
  'message' : string,
  'timestamp' : bigint,
  'senderName' : string,
  'senderRole' : string,
  'senderId' : string,
}
export interface Coordinator {
  'id' : CoordinatorId,
  'name' : string,
  'email' : string,
}
export type CoordinatorId = string;
export interface Event {
  'id' : EventId,
  'status' : string,
  'title' : string,
  'date' : bigint,
  'createdBy' : CoordinatorId,
  'time' : bigint,
  'description' : string,
  'requiredHours' : bigint,
  'location' : string,
  'eventType' : string,
}
export type EventId = string;
export type ExternalBlob = Uint8Array;
export interface Feedback {
  'id' : FeedbackId,
  'eventId' : [] | [EventId],
  'submittedAt' : bigint,
  'coordinatorResponse' : [] | [string],
  'volunteerId' : VolunteerId,
  'message' : string,
  'respondedAt' : [] | [bigint],
}
export type FeedbackId = string;
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'targetAll' : boolean,
  'message' : string,
}
export type NotificationId = string;
export interface Photo {
  'id' : PhotoId,
  'eventId' : EventId,
  'title' : string,
  'blobId' : ExternalBlob,
  'uploadedAt' : bigint,
}
export type PhotoId = string;
export type Role = { 'coordinator' : null } |
  { 'volunteer' : null };
export interface ServiceHours {
  'id' : ServiceHoursId,
  'eventId' : EventId,
  'hours' : bigint,
  'date' : bigint,
  'volunteerId' : VolunteerId,
}
export type ServiceHoursId = string;
export interface UserProfile {
  'userId' : string,
  'name' : string,
  'role' : Role,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Volunteer {
  'id' : VolunteerId,
  'totalHours' : bigint,
  'name' : string,
  'joinedAt' : bigint,
  'email' : string,
  'rollNumber' : string,
  'phone' : string,
  'department' : string,
}
export type VolunteerId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<[string, string, ExternalBlob], Photo>,
  'addServiceHours' : ActorMethod<
    [string, string, bigint, bigint],
    ServiceHours
  >,
  'adminLogin' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'checkIfVolunteerAttendedEvent' : ActorMethod<[string, string], boolean>,
  'createCoordinator' : ActorMethod<[string, string], Coordinator>,
  'createCoordinatorAsAdmin' : ActorMethod<
    [string, string, string, string],
    Coordinator
  >,
  'createEvent' : ActorMethod<
    [
      string,
      string,
      bigint,
      CoordinatorId,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    Event
  >,
  'createNotification' : ActorMethod<[string, string, boolean], Notification>,
  'deleteCoordinator' : ActorMethod<[string], undefined>,
  'deleteCoordinatorAsAdmin' : ActorMethod<[string, string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deletePhoto' : ActorMethod<[string], undefined>,
  'generateEventAttendanceSummary' : ActorMethod<[string], bigint>,
  'generateEventAttendanceSummaryAsAdmin' : ActorMethod<
    [string, string],
    bigint
  >,
  'generateVolunteerHoursSummary' : ActorMethod<[], Array<[string, bigint]>>,
  'generateVolunteerHoursSummaryAsAdmin' : ActorMethod<
    [string],
    Array<[string, bigint]>
  >,
  'getAllCertificates' : ActorMethod<[], Array<Certificate>>,
  'getAllCoordinators' : ActorMethod<[], Array<Coordinator>>,
  'getAllCoordinatorsAsAdmin' : ActorMethod<[string], Array<Coordinator>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllPhotos' : ActorMethod<[], Array<Photo>>,
  'getAllServiceHoursForEvent' : ActorMethod<[string], Array<ServiceHours>>,
  'getAllVolunteers' : ActorMethod<[], Array<Volunteer>>,
  'getAllVolunteersAsAdmin' : ActorMethod<[string], Array<Volunteer>>,
  'getAttendanceForEvent' : ActorMethod<[string], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertificatesByVolunteer' : ActorMethod<[string], Array<Certificate>>,
  'getChatMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getCoordinator' : ActorMethod<[string], Coordinator>,
  'getEvent' : ActorMethod<[string], Event>,
  'getLeaderboard' : ActorMethod<[], Array<Volunteer>>,
  'getMyAttendance' : ActorMethod<[], Array<Attendance>>,
  'getMyCertificates' : ActorMethod<[], Array<Certificate>>,
  'getMyFeedback' : ActorMethod<[], Array<Feedback>>,
  'getMyTotalServiceHours' : ActorMethod<[], bigint>,
  'getMyVolunteerProfile' : ActorMethod<[], [] | [Volunteer]>,
  'getPhotosByEvent' : ActorMethod<[string], Array<Photo>>,
  'getServiceHoursByVolunteer' : ActorMethod<[string], Array<ServiceHours>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVolunteerById' : ActorMethod<[string], Volunteer>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'issueCertificate' : ActorMethod<[string, bigint, boolean], Certificate>,
  'loginCoordinator' : ActorMethod<[string], [] | [Coordinator]>,
  'loginVolunteer' : ActorMethod<[string], [] | [Volunteer]>,
  'manuallyMarkAttendance' : ActorMethod<[string, string], Attendance>,
  'markAttendance' : ActorMethod<[string], Attendance>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'registerVolunteer' : ActorMethod<
    [string, string, string, string, string],
    Volunteer
  >,
  'respondToFeedback' : ActorMethod<[string, string], Feedback>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'sendMessage' : ActorMethod<[string], ChatMessage>,
  'submitFeedback' : ActorMethod<[[] | [EventId], string], Feedback>,
  'updateEvent' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      CoordinatorId,
      string,
      bigint,
      bigint,
      string,
      string,
    ],
    Event
  >,
  'updateVolunteerProfile' : ActorMethod<[string, string, string], Volunteer>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];