/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type FeedbackId = string;
export interface Certificate {
    id: CertificateId;
    hoursCompleted: bigint;
    downloadable: boolean;
    volunteerId: VolunteerId;
    issuedAt: bigint;
}
export type PhotoId = string;
export type EventId = string;
export interface Attendance {
    id: AttendanceId;
    eventId: EventId;
    markedBy: string;
    volunteerId: VolunteerId;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Feedback {
    id: FeedbackId;
    eventId?: EventId;
    submittedAt: bigint;
    coordinatorResponse?: string;
    volunteerId: VolunteerId;
    message: string;
    respondedAt?: bigint;
}
export type VolunteerId = string;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Event {
    id: EventId;
    status: string;
    title: string;
    date: bigint;
    createdBy: CoordinatorId;
    time: bigint;
    description: string;
    requiredHours: bigint;
    location: string;
    eventType: string;
}
export type CertificateId = string;
export type AttendanceId = string;
export type NotificationId = string;
export interface Notification {
    id: NotificationId;
    title: string;
    createdAt: bigint;
    createdBy: string;
    targetAll: boolean;
    message: string;
}
export type CoordinatorId = string;
export interface ChatMessage {
    id: string;
    message: string;
    timestamp: bigint;
    senderName: string;
    senderRole: string;
    senderId: string;
}
export interface Coordinator {
    id: CoordinatorId;
    name: string;
    email: string;
}
export interface Volunteer {
    id: VolunteerId;
    totalHours: bigint;
    name: string;
    joinedAt: bigint;
    email: string;
    rollNumber: string;
    phone: string;
    department: string;
}
export interface ServiceHours {
    id: ServiceHoursId;
    eventId: EventId;
    hours: bigint;
    date: bigint;
    volunteerId: VolunteerId;
}
export type ServiceHoursId = string;
export interface UserProfile {
    userId: string;
    name: string;
    role: Role;
    email: string;
}
export interface Photo {
    id: PhotoId;
    eventId: EventId;
    title: string;
    blobId: ExternalBlob;
    uploadedAt: bigint;
}
export enum Role {
    coordinator = "coordinator",
    volunteer = "volunteer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPhoto(eventId: string, title: string, blobId: ExternalBlob): Promise<Photo>;
    addServiceHours(volunteerId: string, eventId: string, hours: bigint, date: bigint): Promise<ServiceHours>;
    adminLogin(password: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeAdminPassword(oldPassword: string, newPassword: string): Promise<boolean>;
    checkIfVolunteerAttendedEvent(volunteerId: string, eventId: string): Promise<boolean>;
    createCoordinator(name: string, email: string): Promise<Coordinator>;
    createCoordinatorAsAdmin(adminPwd: string, name: string, email: string, coordPassword: string): Promise<Coordinator>;
    createEvent(title: string, eventType: string, requiredHours: bigint, createdBy: CoordinatorId, status: string, date: bigint, time: bigint, location: string, description: string): Promise<Event>;
    createNotification(title: string, message: string, targetAll: boolean): Promise<Notification>;
    deleteCoordinator(id: string): Promise<void>;
    deleteCoordinatorAsAdmin(adminPwd: string, id: string): Promise<void>;
    deleteEvent(id: string): Promise<void>;
    deletePhoto(id: string): Promise<void>;
    deleteVolunteer(id: string): Promise<void>;
    deleteVolunteerAsAdmin(adminPwd: string, id: string): Promise<void>;
    generateEventAttendanceSummary(eventId: string): Promise<bigint>;
    generateEventAttendanceSummaryAsAdmin(adminPwd: string, eventId: string): Promise<bigint>;
    generateVolunteerHoursSummary(): Promise<Array<[string, bigint]>>;
    generateVolunteerHoursSummaryAsAdmin(adminPwd: string): Promise<Array<[string, bigint]>>;
    getAllCertificates(): Promise<Array<Certificate>>;
    getAllCoordinators(): Promise<Array<Coordinator>>;
    getAllCoordinatorsAsAdmin(adminPwd: string): Promise<Array<Coordinator>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllNotifications(): Promise<Array<Notification>>;
    getAllPhotos(): Promise<Array<Photo>>;
    getAllServiceHoursForEvent(eventId: string): Promise<Array<ServiceHours>>;
    getAllVolunteers(): Promise<Array<Volunteer>>;
    getAllVolunteersAsAdmin(adminPwd: string): Promise<Array<Volunteer>>;
    getAttendanceForEvent(eventId: string): Promise<Array<Attendance>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCertificatesByVolunteer(volunteerId: string): Promise<Array<Certificate>>;
    getChatMessages(): Promise<Array<ChatMessage>>;
    getCoordinator(id: string): Promise<Coordinator>;
    getEvent(id: string): Promise<Event>;
    getLeaderboard(): Promise<Array<Volunteer>>;
    getMyAttendance(): Promise<Array<Attendance>>;
    getMyCertificates(): Promise<Array<Certificate>>;
    getMyFeedback(): Promise<Array<Feedback>>;
    getMyTotalServiceHours(): Promise<bigint>;
    getMyVolunteerProfile(): Promise<Volunteer | null>;
    getPhotosByEvent(eventId: string): Promise<Array<Photo>>;
    getServiceHoursByVolunteer(volunteerId: string): Promise<Array<ServiceHours>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUpcomingEvents(): Promise<Array<Event>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVolunteerById(id: string): Promise<Volunteer>;
    isCallerAdmin(): Promise<boolean>;
    issueCertificate(volunteerId: string, hoursCompleted: bigint, downloadable: boolean): Promise<Certificate>;
    loginCoordinator(email: string, password: string): Promise<Coordinator | null>;
    loginVolunteer(email: string, password: string): Promise<Volunteer | null>;
    manuallyMarkAttendance(volunteerId: string, eventId: string): Promise<Attendance>;
    markAttendance(eventId: string): Promise<Attendance>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    registerVolunteer(name: string, email: string, rollNumber: string, department: string, phone: string, password: string): Promise<Volunteer>;
    respondToFeedback(id: string, response: string): Promise<Feedback>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setMyPassword(email: string, newPassword: string): Promise<boolean>;
    seedSampleData(): Promise<void>;
    sendMessage(message: string): Promise<ChatMessage>;
    submitFeedback(eventId: EventId | null, message: string): Promise<Feedback>;
    updateEvent(id: string, title: string, eventType: string, requiredHours: bigint, createdBy: CoordinatorId, status: string, date: bigint, time: bigint, location: string, description: string): Promise<Event>;
    updateVolunteerProfile(name: string, phone: string, department: string): Promise<Volunteer>;
    updateVolunteerById(id: string, name: string, phone: string, department: string, rollNumber: string): Promise<Volunteer>;
}
import type { Coordinator as _Coordinator, EventId as _EventId, ExternalBlob as _ExternalBlob, Feedback as _Feedback, FeedbackId as _FeedbackId, Photo as _Photo, PhotoId as _PhotoId, Role as _Role, UserProfile as _UserProfile, UserRole as _UserRole, Volunteer as _Volunteer, VolunteerId as _VolunteerId, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPhoto(arg0: string, arg1: string, arg2: ExternalBlob): Promise<Photo> {
        if (this.processError) {
            try {
                const result = await this.actor.addPhoto(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Photo_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPhoto(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Photo_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addServiceHours(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<ServiceHours> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceHours(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceHours(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminLogin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async checkIfVolunteerAttendedEvent(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIfVolunteerAttendedEvent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIfVolunteerAttendedEvent(arg0, arg1);
            return result;
        }
    }
    async createCoordinator(arg0: string, arg1: string): Promise<Coordinator> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoordinator(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoordinator(arg0, arg1);
            return result;
        }
    }
    async createCoordinatorAsAdmin(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Coordinator> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoordinatorAsAdmin(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoordinatorAsAdmin(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: bigint, arg3: CoordinatorId, arg4: string, arg5: bigint, arg6: bigint, arg7: string, arg8: string): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async createNotification(arg0: string, arg1: string, arg2: boolean): Promise<Notification> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCoordinator(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoordinator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoordinator(arg0);
            return result;
        }
    }
    async deleteCoordinatorAsAdmin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoordinatorAsAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoordinatorAsAdmin(arg0, arg1);
            return result;
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deletePhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhoto(arg0);
            return result;
        }
    }
    async deleteVolunteer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVolunteer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVolunteer(arg0);
            return result;
        }
    }
    async deleteVolunteerAsAdmin(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVolunteerAsAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVolunteerAsAdmin(arg0, arg1);
            return result;
        }
    }
    async generateEventAttendanceSummary(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateEventAttendanceSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateEventAttendanceSummary(arg0);
            return result;
        }
    }
    async generateEventAttendanceSummaryAsAdmin(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateEventAttendanceSummaryAsAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateEventAttendanceSummaryAsAdmin(arg0, arg1);
            return result;
        }
    }
    async generateVolunteerHoursSummary(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateVolunteerHoursSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateVolunteerHoursSummary();
            return result;
        }
    }
    async generateVolunteerHoursSummaryAsAdmin(arg0: string): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateVolunteerHoursSummaryAsAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateVolunteerHoursSummaryAsAdmin(arg0);
            return result;
        }
    }
    async getAllCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCertificates();
            return result;
        }
    }
    async getAllCoordinators(): Promise<Array<Coordinator>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoordinators();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoordinators();
            return result;
        }
    }
    async getAllCoordinatorsAsAdmin(arg0: string): Promise<Array<Coordinator>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoordinatorsAsAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoordinatorsAsAdmin(arg0);
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return result;
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return result;
        }
    }
    async getAllPhotos(): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhotos();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhotos();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServiceHoursForEvent(arg0: string): Promise<Array<ServiceHours>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceHoursForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceHoursForEvent(arg0);
            return result;
        }
    }
    async getAllVolunteers(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVolunteers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVolunteers();
            return result;
        }
    }
    async getAllVolunteersAsAdmin(arg0: string): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVolunteersAsAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVolunteersAsAdmin(arg0);
            return result;
        }
    }
    async getAttendanceForEvent(arg0: string): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAttendanceForEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAttendanceForEvent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCertificatesByVolunteer(arg0: string): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertificatesByVolunteer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertificatesByVolunteer(arg0);
            return result;
        }
    }
    async getChatMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatMessages();
            return result;
        }
    }
    async getCoordinator(arg0: string): Promise<Coordinator> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoordinator(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoordinator(arg0);
            return result;
        }
    }
    async getEvent(arg0: string): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<Volunteer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyAttendance(): Promise<Array<Attendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttendance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttendance();
            return result;
        }
    }
    async getMyCertificates(): Promise<Array<Certificate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCertificates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCertificates();
            return result;
        }
    }
    async getMyFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyFeedback();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyFeedback();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTotalServiceHours(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTotalServiceHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTotalServiceHours();
            return result;
        }
    }
    async getMyVolunteerProfile(): Promise<Volunteer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVolunteerProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVolunteerProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPhotosByEvent(arg0: string): Promise<Array<Photo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhotosByEvent(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhotosByEvent(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceHoursByVolunteer(arg0: string): Promise<Array<ServiceHours>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceHoursByVolunteer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceHoursByVolunteer(arg0);
            return result;
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVolunteerById(arg0: string): Promise<Volunteer> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteerById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteerById(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async issueCertificate(arg0: string, arg1: bigint, arg2: boolean): Promise<Certificate> {
        if (this.processError) {
            try {
                const result = await this.actor.issueCertificate(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueCertificate(arg0, arg1, arg2);
            return result;
        }
    }
    async loginCoordinator(arg0: string, arg1: string): Promise<Coordinator | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginCoordinator(arg0, arg1);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginCoordinator(arg0, arg1);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginVolunteer(arg0: string, arg1: string): Promise<Volunteer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginVolunteer(arg0, arg1);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginVolunteer(arg0, arg1);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async manuallyMarkAttendance(arg0: string, arg1: string): Promise<Attendance> {
        if (this.processError) {
            try {
                const result = await this.actor.manuallyMarkAttendance(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.manuallyMarkAttendance(arg0, arg1);
            return result;
        }
    }
    async markAttendance(arg0: string): Promise<Attendance> {
        if (this.processError) {
            try {
                const result = await this.actor.markAttendance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAttendance(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async registerVolunteer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Volunteer> {
        if (this.processError) {
            try {
                const result = await this.actor.registerVolunteer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerVolunteer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async respondToFeedback(arg0: string, arg1: string): Promise<Feedback> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToFeedback(arg0, arg1);
                return from_candid_Feedback_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToFeedback(arg0, arg1);
            return from_candid_Feedback_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setMyPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setMyPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMyPassword(arg0, arg1);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async sendMessage(arg0: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return result;
        }
    }
    async submitFeedback(arg0: EventId | null, arg1: string): Promise<Feedback> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Feedback_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(to_candid_opt_n34(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Feedback_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEvent(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: CoordinatorId, arg5: string, arg6: bigint, arg7: bigint, arg8: string, arg9: string): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateVolunteerProfile(arg0: string, arg1: string, arg2: string): Promise<Volunteer> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVolunteerProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVolunteerProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async updateVolunteerById(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Volunteer> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVolunteerById(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVolunteerById(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Feedback_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_Photo_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Photo): Promise<Photo> {
    return await from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EventId]): EventId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Volunteer]): Volunteer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Coordinator]): Coordinator | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PhotoId;
    eventId: _EventId;
    title: string;
    blobId: _ExternalBlob;
    uploadedAt: bigint;
}): Promise<{
    id: PhotoId;
    eventId: EventId;
    title: string;
    blobId: ExternalBlob;
    uploadedAt: bigint;
}> {
    return {
        id: value.id,
        eventId: value.eventId,
        title: value.title,
        blobId: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blobId),
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FeedbackId;
    eventId: [] | [_EventId];
    submittedAt: bigint;
    coordinatorResponse: [] | [string];
    volunteerId: _VolunteerId;
    message: string;
    respondedAt: [] | [bigint];
}): {
    id: FeedbackId;
    eventId?: EventId;
    submittedAt: bigint;
    coordinatorResponse?: string;
    volunteerId: VolunteerId;
    message: string;
    respondedAt?: bigint;
} {
    return {
        id: value.id,
        eventId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.eventId)),
        submittedAt: value.submittedAt,
        coordinatorResponse: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.coordinatorResponse)),
        volunteerId: value.volunteerId,
        message: value.message,
        respondedAt: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.respondedAt))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    name: string;
    role: _Role;
    email: string;
}): {
    userId: string;
    name: string;
    role: Role;
    email: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: from_candid_Role_n24(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coordinator: null;
} | {
    volunteer: null;
}): Role {
    return "coordinator" in value ? Role.coordinator : "volunteer" in value ? Role.volunteer : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Photo>): Promise<Array<Photo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Photo_n9(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Role_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventId | null): [] | [_EventId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    name: string;
    role: Role;
    email: string;
}): {
    userId: string;
    name: string;
    role: _Role;
    email: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: to_candid_Role_n32(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    coordinator: null;
} | {
    volunteer: null;
} {
    return value == Role.coordinator ? {
        coordinator: null
    } : value == Role.volunteer ? {
        volunteer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
